Repository exoego/esbuild-bundle-analyzer, pull requests merged in 2024-08, with the labels that each got.

#65 fix: correct variable name for show_no_change in action.yaml
  action.yaml
Labels: bug

#72 fix: add hidden comment at start instead of end to avoid truncation
  dist/index.mjs
  src/compare.ts
Labels: bug

#73 chore: added comment
  dist/index.mjs
  src/compare.ts
Labels: chore

#78 doc: show_no_change should be false by default so users can look all at a glance
  README.md
Labels: documentation

#80 feat: add showTotalChanges
  README.md
  __tests__/no-base.test.ts
  __tests__/with-base.test.ts
  action.yaml
  dist/index.mjs
  src/compare.ts
  src/index.ts
  src/types.ts
Labels: enhancement

#81 refactor: extract utility
  dist/index.mjs
  src/index.ts
  src/utils.ts
Labels: chore

#82 feat: add `include_size_comparison` option
  README.md
  __tests__/no-base.test.ts
  __tests__/with-base.test.ts
  action.yaml
  dist/index.mjs
  src/compare.ts
  src/index.ts
  src/types.ts
Labels: enhancement

#83 chore: address biome deprecation
  package.json
Labels: chore

#84 bugfix: show_no_change should not default to true
  action.yaml
  dist/index.mjs
  src/index.ts
Labels: bug
